version: '3.3'
services:
  openems-backend:
    image: openems-backend
    ports:
      - 8075:8075 # Backend2Backend.Rest
      - 8076:8076 # Backend2Backend.Websocket
      - 8079:8079 # Apache Felix Web Console
      - 8081:8081 # Edge.Websocket
      - 8082:8082 # Ui.Websocket
    networks:
      - openems
  openems-ui-backend:
    image: openems-ui-backend
    depends_on:
      - openems-backend
    ports:
      - 4202:8000
    networks:
      - openems
  influxdb:
    image: influxdb:latest  # Using InfluxDB version 2.0
    container_name: openems-influxdb
    ports:
      - "8086:8086"  # Default port for InfluxDB
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    volumes:
      - influxdb-data:/var/lib/influxdb2  # Persist data
    restart: unless-stopped
    networks:
      - openems
networks:
  openems:
    driver: bridge