version: '3.3'
services:
  openems-edge:
    image: openems-edge
    ports:
      - 8080:8080 # Apache Felix Web Console
      - 8084:8084 # Controller.Api.Rest.ReadOnly
      - 8085:8085 # Controller.Api.Websocket
      - 8887:8887 # OCPP 1.6J Server
    volumes:
      - ./openems-edge/config.d:/opt/openems-edge/config.d
    networks:
      - openems

  openems-ui-edge:
    image: openems-ui-edge
    depends_on:
      - openems-edge
    ports:
      - 4201:8000
    networks:
      - openems

  openems-influxdb:
    image: influxdb:latest
    container_name: openems-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=data-2
    volumes:
      - influxdb-data:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - openems

  modbus-server:
    image: modbus-server
    ports:
      - 5021:5020
    networks:
      - openems
networks:
  openems:
    driver: bridge

volumes:
  influxdb-data:
